In [1]:
import nltk 
import pandas as pd 
import sys

In [2]:
print('hello')

hello

In [3]:
import spacy
print(spacy.__version__)

3.8.14

In [4]:
df = pd.read_csv('ham_spam_nlp_dataset_1000.csv')
df.head()

,id,label,subject,email
0,1,spam,Free Gift,Exclusive offer! Get 30% off on premium produc...
1,2,spam,Exclusive Deal,You have been selected to receive a $10000 rew...
2,3,spam,Win Big Today,Invest in our crypto platform and double your ...
3,4,ham,Meeting Reminder,Happy birthday! Hope you have a wonderful day ...
4,5,ham,Class Notes,I've shared the project files in the team driv...

In [5]:
df['Email'] = df['email'].str.lower()
df.drop(['email'],axis = 1)

,id,label,subject,Email
0,1,spam,Free Gift,exclusive offer! get 30% off on premium produc...
1,2,spam,Exclusive Deal,you have been selected to receive a $10000 rew...
2,3,spam,Win Big Today,invest in our crypto platform and double your ...
3,4,ham,Meeting Reminder,happy birthday! hope you have a wonderful day ...
4,5,ham,Class Notes,i've shared the project files in the team driv...
...,...,...,...,...
995,996,ham,Meeting Reminder,happy birthday! hope you have a wonderful day ...
996,997,ham,Lunch Plan,"hi priya, just a reminder that our meeting is ..."
997,998,spam,Congratulations!,your parcel is waiting. confirm your shipping ...
998,999,ham,Project Update,happy birthday! hope you have a wonderful day ...
999,1000,ham,Doctor Appointment,please find the attached report for this week'...

In [8]:
df.head()

,id,label,subject,email,Email
0,1,spam,Free Gift,Exclusive offer! Get 30% off on premium produc...,exclusive offer! get 30% off on premium produc...
1,2,spam,Exclusive Deal,You have been selected to receive a $10000 rew...,you have been selected to receive a $10000 rew...
2,3,spam,Win Big Today,Invest in our crypto platform and double your ...,invest in our crypto platform and double your ...
3,4,ham,Meeting Reminder,Happy birthday! Hope you have a wonderful day ...,happy birthday! hope you have a wonderful day ...
4,5,ham,Class Notes,I've shared the project files in the team driv...,i've shared the project files in the team driv...

In [7]:
import string

In [12]:
def remove_punct(email):
    clean = [c for c in email if c not in string.punctuation]
    return"".join(clean)

df['clean_msg'] = df['email'].apply(remove_punct)

In [13]:
df.head()

,id,label,subject,email,Email,clean_msg
0,1,spam,Free Gift,Exclusive offer! Get 30% off on premium produc...,exclusive offer! get 30% off on premium produc...,Exclusive offer Get 30 off on premium products...
1,2,spam,Exclusive Deal,You have been selected to receive a $10000 rew...,you have been selected to receive a $10000 rew...,You have been selected to receive a 10000 rewa...
2,3,spam,Win Big Today,Invest in our crypto platform and double your ...,invest in our crypto platform and double your ...,Invest in our crypto platform and double your ...
3,4,ham,Meeting Reminder,Happy birthday! Hope you have a wonderful day ...,happy birthday! hope you have a wonderful day ...,Happy birthday Hope you have a wonderful day w...
4,5,ham,Class Notes,I've shared the project files in the team driv...,i've shared the project files in the team driv...,Ive shared the project files in the team drive...

In [21]:
nltk.download("punkt")
from nltk.tokenize import word_tokenize 



df["tokens"] = df["clean_msg"].apply(word_tokenize)
print(df["tokens"].head(2).values)

[list(['Exclusive', 'offer', 'Get', '30', 'off', 'on', 'premium', 'products', 'Buy', 'now'])
 list(['You', 'have', 'been', 'selected', 'to', 'receive', 'a', '10000', 'reward', 'Click', 'the', 'link', 'to', 'verify', 'your', 'account'])]

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\ASUS\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!

In [27]:
from nltk.corpus import stopwords
nltk.download('stopwords')

stop_words = set(stopwords.words('english'))
def filter_stops(token_list):
    return[w for w in token_list if w not in stop_words]
df["clean_tokens"] =  df["tokens"].apply(filter_stops)
print(df['clean_tokens'].head(5).values)

[list(['Exclusive', 'offer', 'Get', '30', 'premium', 'products', 'Buy'])
 list(['You', 'selected', 'receive', '10000', 'reward', 'Click', 'link', 'verify', 'account'])
 list(['Invest', 'crypto', 'platform', 'double', 'investment', '7', 'days'])
 list(['Happy', 'birthday', 'Hope', 'wonderful', 'day', 'family'])
 list(['Ive', 'shared', 'project', 'files', 'team', 'drive', 'Please', 'review', 'tomorrow'])]

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\ASUS\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [28]:
from nltk.stem import WordNetLemmatizer
nltk.download('wordnet')

lemmatizer = WordNetLemmatizer()
def lemmatize_tokens(token_list):
    return[lemmatizer.lemmatize(w) for w in token_list]

df['final_tokens'] = df['clean_tokens'].apply(lemmatize_tokens)
print(df['final_tokens'].head(5).values)

[list(['Exclusive', 'offer', 'Get', '30', 'premium', 'product', 'Buy'])
 list(['You', 'selected', 'receive', '10000', 'reward', 'Click', 'link', 'verify', 'account'])
 list(['Invest', 'crypto', 'platform', 'double', 'investment', '7', 'day'])
 list(['Happy', 'birthday', 'Hope', 'wonderful', 'day', 'family'])
 list(['Ive', 'shared', 'project', 'file', 'team', 'drive', 'Please', 'review', 'tomorrow'])]

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\ASUS\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!